// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '<b>{0}</b>: {1}',
    'defaultAlt': '<b>{0}</b>',
    'example:important': '<h1>^2{0}</h1>',
    'weazel':'<div style="padding: 1vw;background: linear-gradient(-90deg,#3178f9, #1935becf);border-radius: 20px;box-shadow: 0 0 10px #2464d8;max-width: 730px;"><span style="display:block; margin-bottom:20px"><span style="padding:10px;border-radius:10px;background: #0089ff;box-shadow: 0 0 10px #3178f9;"><i class="fa fa-newspaper"></i></span> <b>[WEAZEL NEWS]</b></span> {1}<p style="text-align: right; font-size: 12pt; font-style: italic;"><i class="fa fa-user"></i> {0}</p></div>',
    'announce':'<div style="padding: 1vw;background: linear-gradient(-90deg,#f93154, #be1919bf);border-radius: 20px;box-shadow: 0 0 10px #f93154;max-width: 730px;"><span style="display:block; margin-bottom:20px"><span style="padding:10px;border-radius:10px;background: #f93154;box-shadow: 0 0 10px #f93154;"><i class="fa fa-bullhorn"></i></span> <b>[ANNOUNCEMENT]</b></span> {0}</div>',
  },
  fadeTimeout: 7000,
  suggestionLimit: 5,
  style: {
    background: 'transparent;',
    width: '38%',
    height: '240px',
  }
};
